version: '3'

services:
  db:
    image: postgres
  back:
    build: back
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./back:/usr/src/app
    ports:
      - "8000"
    depends_on:
      - db
  chat:
    build: chat
  front:
    image: node:latest
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd /usr/src/app && npm install && npm run build --production"
